// module MlabsPlutusTemplate.Api, generated by purescript-tsd-gen 0.3.0.0
import * as Control_Promise from "../Control.Promise";
import * as Ctl_Internal_Types_Transaction from "../Ctl.Internal.Types.Transaction";
import * as Data_Unit from "../Data.Unit";
export const payToPassword: (_0: string, _1: string) => Control_Promise.Promise< Ctl_Internal_Types_Transaction.TransactionHash >;
export const spendFromPassword: (_0: Ctl_Internal_Types_Transaction.TransactionHash, _1: string, _2: string) => Data_Unit.Unit;
export const mintTokens: (_0: string, _1: string) => Data_Unit.Unit;
export const burnTokens: (_0: string, _1: string) => Data_Unit.Unit;
export const insertPWTXHash: (_0: string, _1: Ctl_Internal_Types_Transaction.TransactionHash, _2: Array< PWTXHash >) => Array< PWTXHash >;
export const lookupTXHashByPW: (_0: string, _1: Array< PWTXHash >) => PWTXHash | null;
export type /*data*/ PWTXHash = { "$$pursType": "MlabsPlutusTemplate.Api.PWTXHash"; "$$pursTag": "PWTXHash"; "$$abstractMarker": never };
// invalid instance declaration 'newtypePWTXHash_'
export {};
