// Generated by purs bundle 0.14.9
var PS = {};
(function($PS) {
  // Generated by purs version 0.14.9
  "use strict";
  $PS["MlabsPlutusTemplate.Api"] = $PS["MlabsPlutusTemplate.Api"] || {};
  var exports = $PS["MlabsPlutusTemplate.Api"];
  var square = function (n) {
      return n * n | 0;
  };
  exports["square"] = square;
})(PS);
module.exports = PS["MlabsPlutusTemplate.Api"];
